"use client";
// import { Inter } from "next/font/google";
import "./globals.css";
// import 'bootstrap/dist/css/bootstrap.min.css';
// import 'bootstrap-icons/font/bootstrap-icons.css';


// import 'bootstrap/dist/js/bootstrap.bundle.min.js';


// import "mdb-react-ui-kit/dist/css/mdb.min.css";
// import "@fortawesome/fontawesome-free/css/all.min.css";

// import 'bootstrap/dist/js/bootstrap.bundle.min.js'; //bug

// import 'bootstrap-css-only/css/bootstrap.min.css';
// import 'mdbreact/dist/css/mdb.css';


import Topsection from "./overview/mainComp/topsection";
import Footer from "./overview/mainComp/footer";
import { usePathname } from "next/navigation";
import { useEffect } from "react";
import k from "./page.module.css"
import Head from "next/head";



// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();

  useEffect(() => {
    // This sets the background color of the mobile status bar
    let metaTheme = document.querySelector('meta[name="theme-color"]');
    if (!metaTheme) {
      metaTheme = document.createElement('meta');
      metaTheme.name = 'theme-color';
      document.head.appendChild(metaTheme);
    }
    metaTheme.content = '#151b46';

    // Add viewport meta for mobile
    let viewport = document.querySelector('meta[name="viewport"]');
    if (!viewport) {
      viewport = document.createElement('meta');
      viewport.name = 'viewport';
      document.head.appendChild(viewport);
    }
    viewport.content = 'width=device-width, initial-scale=1, viewport-fit=cover, user-scalable=no';

    // For iOS
    let appleMeta = document.querySelector('meta[name="apple-mobile-web-app-status-bar-style"]');
    if (!appleMeta) {
      appleMeta = document.createElement('meta');
      appleMeta.name = 'apple-mobile-web-app-status-bar-style';
      document.head.appendChild(appleMeta);
    }
    appleMeta.content = 'black-translucent';

    // No need to clean up meta tags as they may be used by other components
    return () => {};
  }, []);

  if (pathname === "/signup") {
    return (
      <html lang="en">
        <body>{children}</body>
      </html>
    );
  }

  if (pathname === "/changepassword") {
    return (
      <html lang="en">
        <body>{children}</body>
      </html>
    );
  }

  if (pathname === "/forgotpassword") {
    return (
      <html lang="en">
        <body>{children}</body>
      </html>
    );
  }

  if (pathname === "/verifyemail") {
    return (
      <html lang="en">
        <body>{children}</body>
      </html>
    );
  }

  if (pathname === "/zkadmin") {
    return (
      <html lang="en">
        <body>{children}</body>
      </html>
    );
  }

  if (pathname === "/suspended") {
    return (
      <html lang="en">
        <body>
          <div>
            <Topsection />
            {children}
          </div>
        </body>
      </html>
    );
  }

  // if (pathname === "/zkadmin/zkprofile") {
  //   return (
  //     <html lang="en">
  //
  //       <body >{children}</body>
  //     </html>
  //   );
  // }

  if (pathname === "/") {
    return (
      <html lang="en">
        <body>
          <div>{children}</div>
        </body>
      </html>
    );
  }

  if (pathname.startsWith("/zk")) {
    return (
      <html lang="en">
        <body>
          <main className={k.main} style={{height:"130vh"}}>
            {/* <Topsection />
            <div style={{ overflow: "auto", height: "100vh" }}>{children}</div> */}
            <div>
              {/* <Header /> */}
              <div style={{ overflow: "auto", height: "150vh" }}>{children}</div>
            </div>

            {/* <Footer /> */}
          </main>
        </body>
      </html>
    );
  }

  if (pathname === "/chat") {
    return (
      <html lang="en">
        <body>
          <main className={k.main} >
            {/* <Topsection /> */}
            <div>{children}</div>
            {/* <Footer /> */}
          </main>
        </body>
      </html>
    );
  }

  if (pathname === "/testimonials") {
    return (
      <html lang="en">
        <body style={{ overflow: "auto", height: "200vh" }}>
          <main className={k.main} style={{height:"130vh", paddingTop: "env(safe-area-inset-top, 0px)"}}>
            {/* <Topsection /> */}
            <div>{children}</div>
            {/* <Footer /> */}
          </main>
        </body>
      </html>
    );
  }

  return (
    <html lang="en">
      <body style={{ overflow: "auto", height: "200vh" }}>
        <main className={k.main} style={{height:"130vh", paddingTop: "env(safe-area-inset-top, 0px)"}}>
          <Topsection />
          <div>{children}</div>
          <Footer />
        </main>
      </body>
    </html>
  );
}
